name: ESLint

on:
  push:
    branches: [ "master", m* ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '18 16 * * 6'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install modules
        run: npm ci
      
      - name: Run ESlint
        run: eslint . --ext .js,.jsx,.ts,.tsx
